# Generated by Django 5.2 on 2025-05-06 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categoria_peca", "0001_initial"),
        ("fornecedor", "0001_initial"),
        ("local_armazenamento", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Peca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("codigo", models.CharField(max_length=50)),
                ("descricao", models.TextField(max_length=500)),
                ("qtd_minima", models.IntegerField(blank=True, default=0, null=True)),
                ("unidade", models.CharField(max_length=50)),
                (
                    "id_categoria_peca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categoria_peca.categoriapeca",
                    ),
                ),
                (
                    "id_fornecedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fornecedor.fornecedor",
                    ),
                ),
                (
                    "id_local_armazenamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="local_armazenamento.localarmazenamento",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "pecas",
                "db_table": "peca",
                "ordering": ["nome"],
            },
        ),
    ]
