# Generated by Django 5.2 on 2025-05-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peca", "0003_alter_peca_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="peca",
            name="foto",
            field=models.ImageField(blank=True, upload_to="foto/%Y/%m/%d/"),
        ),
    ]
