# Generated by Django 5.2.1 on 2025-05-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peca", "0004_peca_foto"),
    ]

    operations = [
        migrations.AddField(
            model_name="peca",
            name="valor",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
