# Generated by Django 5.2.3 on 2025-07-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peca", "0005_peca_valor"),
    ]

    operations = [
        migrations.AddField(
            model_name="peca",
            name="qtd_estoque",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
