# Generated by Django 5.2 on 2025-05-06 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("peca", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField(blank=True, default=0, null=True)),
                ("data_hora_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "id_peca",
                    models.ForeignKey(
                        blank=True,
                        default=0,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="peca.peca",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "estoques",
                "db_table": "estoque",
            },
        ),
    ]
