# Generated by Django 5.2 on 2025-05-06 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0001_initial"),
        ("peca", "0003_alter_peca_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estoque",
            name="id_peca",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="peca.peca",
            ),
        ),
        migrations.AlterModelTable(
            name="estoque",
            table="estoque",
        ),
    ]
