# Generated by Django 5.2.3 on 2025-07-03 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0002_alter_estoque_id_peca_alter_estoque_table"),
        ("peca", "0005_peca_valor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estoque",
            name="id_peca",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="peca.peca",
            ),
        ),
    ]
