# Generated by Django 5.2.3 on 2025-07-11 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0003_alter_estoque_id_peca"),
        ("peca", "0006_peca_qtd_estoque"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estoque",
            name="id_peca",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="peca.peca",
            ),
        ),
    ]
