# Generated by Django 5.2 on 2025-05-06 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("peca", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovimentacaoEstoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=200)),
                ("data_hora", models.DateTimeField(auto_now=True)),
                ("quantidade", models.IntegerField()),
                ("responsavel", models.CharField(max_length=100)),
                (
                    "id_peca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="peca.peca"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "movimentacoes_estoque",
                "db_table": "movimentacao_estoque",
                "ordering": ["tipo"],
            },
        ),
    ]
