# Generated by Django 5.2 on 2025-05-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoriaPeca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "categorias_pecas",
                "db_table": "categoria_peca",
                "ordering": ["nome"],
            },
        ),
    ]
