# Generated by Django 5.2 on 2025-05-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=100, null=True)),
                ("contato", models.CharField(blank=True, max_length=100, null=True)),
                ("endereco", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name_plural": "fornecedores",
                "db_table": "fornecedor",
                "ordering": ["nome"],
            },
        ),
    ]
