# Generated by Django 5.2 on 2025-05-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LocalArmazenamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("setor", models.CharField(blank=True, max_length=200, null=True)),
                ("estante", models.CharField(blank=True, max_length=50, null=True)),
                ("prateleira", models.CharField(blank=True, max_length=50, null=True)),
                ("descricao", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name_plural": "locais_armazenamento",
                "db_table": "local_armazenamento",
                "ordering": ["setor"],
            },
        ),
    ]
