# Generated by Django 5.2.3 on 2025-07-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("local_armazenamento", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="localarmazenamento",
            name="cor_referencia",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
